branches:
  except:
    - gh-pages
language: perl
sudo: false
perl:
  - "blead"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
#  - "5.12"
#  - "5.10"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
#  - cpanm --notest Test::Code::TidyAll 
#  - cpanm --notest Test::Perl::Critic
#  - cpanm --notest Test::Version
services:
  - elasticsearch
script:
  - prove -lv
