branches:
  except:
    - gh-pages
language: perl
sudo: false
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  - cpanm --notest Test::Deep
  - cpanm --notest Test::Code::TidyAll 
services:
  - elasticsearch
script:
  - prove -lv
